version: "3"

services:
  tests:
    # user: 1000:1000

    build:
      dockerfile: Dockerfile.test
      context: ./

    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.netrc:/root/.netrc
      - ./:/app

    environment:
      SSH_AUTH_SOCK: /ssh-agent
    env_file: ".env"
    working_dir: "/app"
    external_links:
      - divio-local-lb:api.local.aldryn.net
      - divio-local-lb:control.local.aldryn.net

  lint:
    image: divio/lint:latest
    user: 1000:1000

    volumes:
      - ./:/app

    env_file: ".env"
    working_dir: "/app"
    command: "/bin/lint"

networks:
  default:
    name: divio-local-lb
    external: true
